name: Update Fork
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stats
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event. "
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: mkdir ct_folder
      - run: cd ct_folder
      - name: Checkout ct
        uses: actions/checkout@v3
        with:
          repository: creativetimofficial/paper-dashboard-laravel
          token: ${{ secrets.CT_TOKEN }}
          path: ct_folder
      - name: Checkout preset
        uses: actions/checkout@v3
        with:
          repository: laravel-frontend-presets/paper-dashboard
          token: ${{ secrets.CT_TOKEN }}
          path: preset_folder
      - name: Configure git and push to preset
        working-directory: /home/runner/work/paper-dashboard-laravel/paper-dashboard-laravel/preset_folder
        run: |
          rsync -r --exclude '.git' /home/runner/work/paper-dashboard-laravel/paper-dashboard-laravel/ct_folder /home/runner/work/paper-dashboard-laravel/paper-dashboard-laravel/preset_folder
          git config --global user.name "CI Bot"
          git config --global user.email "team@mupdivision.com"
          git add .
          git commit -m "merge with fork"
          git push origin HEAD:master --force
        shell: bash
      - run: echo "The fork was updated"   