name: Update Fork
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stats
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Create a Push
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CT }}
      - name: Update code on fork repository
        run: git remote add upstream https://github.com/teamupdivision/creativetimofficial/paper-dashboard-laravel.git
      - run: git fetch upstream
      - run: git checkout upstream/master
      - run: git merge origin/master
      - run: git push upstream/master
      - run: echo "The fork was updated!"   