name: Update Fork
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stats
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: laravel-frontend-presets/paper-dashboard
          token: ${{ secrets.TOKEN_CT }}
      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "team@mupdivision.com"
          git remote add upstream https://github.com/creativetimofficial/paper-dashboard-laravel
        shell: bash
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          git checkout main
          lines=$( git diff main..upstream/main -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git merge upstream/main
            git push
          fi
        shell: bash
      - run: echo "The fork was updated!"   